### ISSUE TITLE
add option to run the test per file

### ISSUE THREAD

**Issue by cowchimp** [gamtiq/grunt-pretest#2]
this is a feature request. feel free to close if you don't accept those.

would be super helpful to decide what task to run based on the result of the test function per file.

``` javascript
grunt.config.merge({
    pretest: {
        src: ['a.js', 'b.js'],
        options: {
            test: function(/* get reference to the current file somehow*/) {
                if (/*run check on the current file*/) {
                    return 'foo:bar';
                } else {
                    return 'baz:qux';
                }
            }
        }
    }
});
```

so it could run, for example, the `foo:bar` task for `a.js` and `baz:qux` for `b.js`.
the check itself could be whatever the user chooses, for example just based on the filename or by reading the contents of the file.

**Comment by gamtiq** [comment]
Thank you for the feature request! It seems quite interesting.
I will consider this feature and will try implementing it asap.
